# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tuyCUJm5EnNRBlY3hrW92uJ1cJIBFtUi
"""

from matplotlib import pyplot as plt
import numpy as np  # linear algebra
import pandas as pd  # data processing
import math

data = pd.read_csv('data_pat.csv', sep=',')
data_t = data[data['ticker'] == 'XOM']
data_c = data_t['close']
data_pr = data_c * 0.005
data_pr = data_pr.to_numpy()
new = []
data_c = data_c.to_numpy()
z = 0
for i in range(len(data_pr)):
    if i == 0:
        new.append(data_c[0])
        continue
    k = i-1
    while k >= z:
        if np.abs(data_c[i] - data_c[k]) > data_pr[i]:
            new.append(np.array(data_c)[i])
            z = i
            break
        k -= 1
    else:
        new.append(0)

# print(new)
print(len(new))
xx = range(0, 100)
plt.figure(figsize=(20, 7))
plt.plot(new[1700:1800], 'red')
# plt.plot(data_c[:100], 'blue')
plt.scatter(xx, data_c[1700:1800])
plt.show()
